function getComputerChoice() {
    //pick a rondom number between 0-2
    let Random = Math.floor(Math.random()*3);
    let RPS = ["rock", "paper", "scissors"]
    return RPS[Random];
    //This function will randomly return Rock Paper or Scissors
    //This will be a romdon number generated by computer
}

//fucntion to play the game
function playRound(pSelection, cSlection){
    if(pSelection === cSlection){
        return "Tie Game!";
    } 
    if(pSelection === "rock"){
        if (cSlection === "scissors"){
            return "You Win!";
        } else{
            return "You Lose!";
        }
    } 
    if (pSelection === "paper") {
        if (cSlection === "rock"){
            return "You Win!";
        } else{
            return "You Lose!";
        }
    } 
    if(pSelection === "scissors"){
        if(cSlection === "paper"){
            return  "You Win!";
        } else{
            return "You Lose!";
        }

    }
    return "You didnt pick rock paper or scissors!";
}

//new function called gam it will keep score and play 5 rounds.
function game(results, score){
    //for loop to play round 5 times 

    //for(let i = 0; i < 5; i++){
        if (results === "You Win!"){
            // add one to the beginning of the array 
            score[0]++;
            console.log("win");
            return score
        }
        if (results === "You Lose!"){
            //add one to the second digit in the array
            score[1]++;
            console.log("lose");
            return score;
        }
        if (results === "Tie Game!"){
            //add one to the end of the array 
            score[2]++;
            console.log("tie");
            return score;
        }
    }

    //if( win > lose && win > tie){
        //console.log("You won the rounds!");
   // }
    //if (lose > win && lose > tie){
       // console.log("You lost the rounds!")
   // }

//}


// Java Script Starts here!
// create a variable that will 
//store the players selection

const body = document.querySelector('#body');
const results = document.createElement("div");
results.classList.add('results');


// Best of 5
//Create a new DIV 
//This one will keep score
let scores = [0,0,0];
const score = document.createElement("div");
score.classList.add("score");



const bRock = document.getElementById("bRock");
bRock.addEventListener("click", () => {
    //get computer choice if rock is clicked
    let cSlection = getComputerChoice() ;
    //assing the text content to rock/paper
    results.textContent =  playRound("rock", cSlection);
    scores = game(results.textContent, scores);
    body.append(results);
    score.textContent = scores[0] + " - " + scores[1] + " - " + scores[2];
    body.appendChild(score);
});

const bPaper =document.getElementById("bPaper");
bPaper.addEventListener("click", () => {
    const cSlection = getComputerChoice() ;
    results.textContent = playRound("paper", cSlection);
    scores = game(results.textContent, scores);
    body.appendChild(results);
    score.textContent = scores[0] + " - " + scores[1] + " - " + scores[2];
    body.appendChild(score);
});

const bScissors = document.getElementById("bScissors");

bScissors.addEventListener("click", () => {
    const cSlection = getComputerChoice() ;
    results.textContent = playRound("scissors", cSlection);
    scores = game(results.textContent, scores);
    body.appendChild(results);
    score.textContent = scores[0] + " - " + scores[1] + " - " + scores[2];
    body.appendChild(score);
});



//Store win, loses, and tie game into variables







